version: '3.4'
services:
  webserver:
    image: "richarvey/nginx-php-fpm:latest"
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html
    environment:
      WEBROOT: /var/www/html/public
  database:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: game
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
