version: '3.4'
services:
  webserver:
    image: "richarvey/nginx-php-fpm:latest"
    ports:
    - "80:80"
    volumes:
    - ./:/var/www/html
    environment:
      WEBROOT: /var/www/html/public
      RUN_SCRIPTS: 1
  database:
    image: postgres
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: game
      POSTGRES_USER: laravel
